 name: python3-awips
 channels:
   - https://conda.anaconda.org/conda-forge
 dependencies:
   - python=3
   - numpy
   - nomkl
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - owslib
   - metpy
   - pint
   - h5py
   - sphinx>=1.3
   - sphinx_rtd_theme
   - nbconvert>=4.1
   - siphon
   - xarray
   - ffmpeg
   - pytest
   - shapely
   - six
   - pip
